//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// ExampleSapera.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_EXAMPLE_SAPERA_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       130
#define IDD_DIALOG_DIAGNOSTIC           131
#define IDD_DIALOG_IMG_STATISTIC        133
#define IDD_DIALOG_HDR                  137
#define IDD_DIALOG_CONTROL_CAMERA       139
#define IDD_DIALOG_PROFILE_HORIZONTAL   143
#define IDD_DIALOG_CHART                143
#define IDD_DIALOG_CONTROL_FRAMEGRABBER 147
#define IDD_DIALOG_ONBOARD_FFC          147
#define IDD_DIALOG_FFC_EDITOR           149
#define IDD_DIALOG_SERVER               151
#define IDD_DIALOG_CLIENT               153
#define IDD_DIALOG_CTRL_FALCON4         155
#define IDD_DIALOG_DEMO_HS2             157
#define IDD_DIALOG_CTRL_LIGHT_ENVIT     159
#define IDB_BITMAP_UI                   161
#define IDB_BITMAP_RESPONSIVITY_OFF     164
#define IDB_BITMAP_RESPONSIVITY_ON      165
#define IDB_BITMAP_SPEED_OFF            166
#define IDB_BITMAP_SPEED_ON             167
#define IDC_CB_FG                       1000
#define IDC_EDIT_BUF_NUM                1001
#define IDC_CB_SDK                      1002
#define IDC_BTN_SNAP                    1003
#define IDC_EDIT_FRAME_NUM              1004
#define IDC_BTN_START_STOP              1005
#define IDC_BTN_SAVE_IMG                1006
#define IDC_EDIT_GRAB_CNT               1007
#define IDC_LIST_STATUS                 1008
#define IDC_ST_DISPLAY                  1009
#define IDC_CHECK_INIT_FREE             1010
#define IDC_CHECK_START_STOP            1011
#define IDC_CHECK_START_STOP2           1012
#define IDC_CHECK_SNAP                  1012
#define IDC_CHECK_PROC                  1013
#define IDC_EDIT_XFER_CYCLE             1014
#define IDC_EDIT_TRASH_CNT              1015
#define IDC_BTN_REFRESH                 1015
#define IDC_EDIT_TRASH_CNT2             1016
#define IDC_EDIT_PROC_CNT               1016
#define IDC_LIST_DIAGNOSTIC             1016
#define IDC_EDIT_PRO_CYCLE              1017
#define IDC_LIST_LANE_STATISTIC         1017
#define IDC_LIST_LANES_STAT             1017
#define IDC_BTN_FIT_DISPLAY             1018
#define IDC_LIST_IMG_INFO               1019
#define IDC_EDIT_FRAME_RATE             1019
#define IDC_EDIT_COPY_TIME              1020
#define IDC_CHECK_LONGRUN               1021
#define IDC_EDIT_WEIGHT                 1022
#define IDC_EDIT_RUN_CNT                1022
#define IDC_SLIDER_WEIGHT               1023
#define IDC_CHK_TRIGGER_MODE            1026
#define IDC_CHK_SCAN_DIRECTION          1027
#define IDC_CB_TDI_MODE                 1028
#define IDC_CB_ANALOG_GAIN              1029
#define IDC_CB_USERSET                  1030
#define IDC_CB_FILE_ACCESS              1031
#define IDC_EDIT_BUF_INDEX              1032
#define IDC_CB_BINNING_HORIZONTAL       1032
#define IDC_EDIT_PLANE_INDEX            1033
#define IDC_CB_BINNING_VERTICAL         1033
#define IDC_BTN_PREV                    1034
#define IDC_CB_FPN_ALGORITHM            1034
#define IDC_BUTTON2                     1035
#define IDC_BTN_NEXT                    1035
#define IDC_LIST_CAM_INFO               1035
#define IDC_BTN_LOAD_LUT                1035
#define IDC_BTN_UI_ON                   1035
#define IDC_BTN_PREV2                   1036
#define IDC_BTN_NEXT2                   1037
#define IDC_CHART_PROFILE_HORIZONTAL    1040
#define IDC_BTN_CAL_FPN                 1041
#define IDC_BTN_CAL_PRNU                1042
#define IDC_BTN_SAVE_USERSET            1043
#define IDC_BTN_CLEAR_FFC               1044
#define IDC_BTN_SHOW_COEFFICIENT        1045
#define IDC_EDIT_INTERNAL_LINERATE      1045
#define IDC_BTN_SET_LINERATE            1046
#define IDC_BTN_PROFILE_HOR             1047
#define IDC_BTN_FILE_DOWNLOAD           1047
#define IDC_CHK_DUAL_FG                 1048
#define IDC_BTN_FILE_UPLOAD             1048
#define IDC_CHART                       1049
#define IDC_BTN_SHOW_CHART              1049
#define IDC_BTN_CALIBRATE               1050
#define IDC_EDIT_TARGET                 1050
#define IDC_BTN_CALIBRATE_BRIGHT        1050
#define IDC_CHK_ENABLE_FFC              1051
#define IDC_BTN_LOAD_FFC                1052
#define IDC_CHART_PROFILE               1052
#define IDC_BTN_SAVE_FFC                1053
#define IDC_BTN_LOAD_FILE               1053
#define IDC_CB_ROW_INDEX                1054
#define IDC_CB_FILE_SELECTOR            1055
#define IDC_BTN_GET_DARK_IMG            1055
#define IDC_BTN_CALIBRATE_DARK          1055
#define IDC_BTN_SAVE_FILE               1056
#define IDC_BTN_GET_BRIGHT_IMG          1056
#define IDC_CB_PROCESS_ALGORITHM        1057
#define IDC_CHK_PROCESS                 1058
#define IDC_CHK_START_SERVER            1063
#define IDC_LIST_CLIENT                 1064
#define IDC_IPADDRESS_SERVER            1065
#define IDC_CHK_START_LONGRUN           1065
#define IDC_EDIT_PORT                   1066
#define IDC_CHK_CONNECT                 1067
#define IDC_CHK_LUT_ENABLE              1071
#define IDC_ST_DISPLAY1                 1074
#define IDC_ST_DISPLAY2                 1075
#define IDC_ST_DISPLAY3                 1076
#define IDC_CHK_START                   1078
#define IDC_EDIT_RED                    1081
#define IDC_EDIT_GREEN                  1082
#define IDC_EDIT_BLUE                   1083
#define IDC_CHK_RED                     1084
#define IDC_CHK_GREEN                   1085
#define IDC_BIT_UI                      1085
#define IDC_CHK_BLUE                    1086
#define IDC_BIT_RESPONSIVITY_OFF        1087
#define IDC_BIT_RESPONSIVITY_ON         1088
#define IDC_BIT_SPEED_OFF               1089
#define IDC_BIT_SPEED_ON                1090
#define ID_DIAGNOSTICTOOL               32771
#define ID_FILE_DIAGNOSTICTOOL          32772
#define ID_IMAGEPROCESSING              32773
#define ID_IMAGEPROCESSING_CONTRAST     32774
#define ID_FILE_EXIT                    32775
#define ID_FILE_TEMP                    32776
#define ID_IMAGEANALYSIS_STATISTIC      32777
#define ID_ONBOARDPROCESSING_HDR        32778
#define ID_CONTROL_LINEAHS              32779
#define ID_CAMERA_LINEAHS               32780
#define ID_LINEAHS_TRIGGERMODE          32781
#define ID_CONTROL_CAMERA               32782
#define ID_IMAGEANALYSIS_PROFILEGRAPH   32783
#define ID_PROFILEGRAPH_HORIZONTAL      32784
#define ID_PROFILEGRAPH_VERTICAL        32785
#define ID_FILE_IMAGEFILELOAD           32786
#define ID_CONTROL_PRNUCOEFFICIENT      32787
#define ID_CONTROL_FRAMEGRABBER         32788
#define ID_CONTROL_FFCCOEFFICIENTEDITOR 32789
#define ID_CONTROL_DATAFORWARDING       32790
#define ID_CONTROL_SERVER_CLIENT        32791
#define ID_CONTROL_SERVER               32792
#define ID_CONTROL_CLIENT               32793
#define ID_CAMERA_LINEAHS32794          32794
#define ID_CAMERA_FALCON4               32795
#define ID_VIEW_HISTOGRAMEQUALIZER      32796
#define ID_ONBOARDPROCESSING_FLATFIELDCORRECTION 32797
#define ID_VIEW                         32798
#define ID_DEMO_LINEAHS2                32799
#define ID_CONTROL_LIGHT                32800
#define ID_LIGHT_ENVIT                  32801
#define ID_LONGRUN_INIT                 32802

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32803
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
